bind 10.200.0.1
port 6379
appendonly no
save ""
protected-mode no
daemonize yes
pidfile /home/udeepa/CLB/ebpf_research/results/redis_broker_6379.pid
logfile "/home/udeepa/CLB/ebpf_research/results/redis_broker.log"
# optional memory policy to avoid disk pressure; tune as needed
maxmemory 0
maxmemory-policy noeviction
